// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          string
	Email       string
	Session     json.RawMessage
	Credentials json.RawMessage
	Verified    bool
	LastLoginAt pgtype.Timestamp
}
